### ISSUE TITLE
Menu should be accessible when pausing the game

### ISSUE THREAD

**Issue by SNException** [SNException/FxGame-2D-Space-Shooter#16]

**Comment by j0sipko** [comment]
i just added this to the game (check my PR). You can now pause game with "P" button, which brings you to main menu with resume option instead of new game. All menu states have got last level state saved in them, so they are able to return to it, though there are still some little issues with inputs while pausing.

**Comment by j0sipko** [comment]
https://github.com/SNException/FxGame-2D-Space-Shooter/pull/21
